config/routes.rb
Rails.application.routes.draw do
  get 'lang/change'

  resources :forums
  get 'add', to: 'forums#add'
  get 'sess/login'

  get 'sess/logout'

  get 'sess/middle'

  get 'sess/out'

  resources :users
  get 'main/main'

  get 'main/view'

  root 'main#main'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum.rb
class Forum < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  validates :login, uniqueness: true

  def self.authenticate(login, password)
    user = find_by_login(login)
    return user if user.password == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :set_locale
  def current_user
    if session[:current_user_id]
      @current_user ||= User.find(session[:current_user_id])
    else
      @current_user = nil
    end
  end

  def set_locale
    I18n.locale = session[:lang] || I18n.default_locale
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    if params[:mes]
      if params[:mes].length > 0
      ans = Message.create(:text => params[:mes], :forum_id => @forum.id, :user_id => current_user.id)
      ans.save
      @str = 1
      redirect_to forum_path
      end
    else
      if params[:str]
        @str = params[:str].to_i
      else
        @str = 1
      end
    end
    @answer = Message.find_by_sql("select * from messages where forum_id = " + @forum.id.to_s + " order by id")
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    if forum_params[:name].length != 0
      @forum = Forum.new(forum_params)
    else
      @problem = 1
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @problem, status: :unprocessable_entity }
      end
    end
    if @forum
      respond_to do |format|
        if @forum.save
          format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
          format.json { render :show, status: :created, location: @forum }
        else
          format.html { render :new }
          format.json { render json: @forum.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name)
    end
end

app/controllers/lang_controller.rb
class LangController < ApplicationController
  def change
    session[:lang] = params[:l]
    redirect_to root_url
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  respond_to :json

  def main
  end

  def view
    @answer = [t(:'We`ve done:'), '', t(:'Messages wrote -'), Message.count, t(:'Users created -'), User.count, t(:'Forums created -'), Forum.count]
    respond_with @answer do |format|
      format.html
      format.json do
        render json: {type: @answer.class, value: @answer}
      end
    end
  end
end

app/controllers/sess_controller.rb
class SessController < ApplicationController
  def login
  end

  def logout
  end

  def middle
    if (!User.find_by_login(params[:login]).nil?) and (user = User.authenticate(params[:login], params[:password]))
      session[:current_user_id] = user.id
      redirect_to root_url
    end
  end

  def out
    @_current_user = session[:current_user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    if user_params[:login].length != 0 and user_params[:password].length != 0
      @user = User.new(user_params)
    else
      @problem = 1
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @problem, status: :unprocessable_entity }
      end
    end
    if @user
      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: t(:'User was created') }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/lang_helper.rb
module LangHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sess_helper.rb
module SessHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forums/_form.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <%= form_with(model: forum, local: true) do |form| %>
      <% if @problem %>
        <div id="error_explanation">
          <p> <%= t(:'Name can`t be empty') %> </p>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :Название %>
        <%= form.text_field :name, id: :forum_name, class: "form-control form-control-sm"%>
      </div>
      <p></p>
      <div class="actions">
        <%= form.submit value: t(:'Create forum'), class: "btn btn-sm btn-primary btn-block btn-light" %>
      </div>
    <% end %>
  </div>
  <div class="col-2"></div>
</div>

app/views/forums/edit.html.erb
<% if current_user.login == 'admin' %>
<%= render 'form', forum: @forum %>
<% end %>

app/views/forums/index.html.erb
<% if current_user.login == 'admin' %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forums.each do |forum| %>
      <tr>
        <td><%= forum.name %></td>
        <td><%= link_to 'Show', forum %></td>
        <td><%= link_to 'Edit', edit_forum_path(forum) %></td>
        <td><%= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/forums/new.html.erb
<%= render 'form', forum: @forum %>

app/views/forums/show.html.erb
<h1 class="align-content-center"><%= @forum.name %></h1>
<% if @str then str = @str else (str = 1; @str = 1) end %>
<table class="table table-borderless">
  <tbody>
  <% if @answer.length != 0 %>
    <% n = [@str * 10, @answer.length].min %>
    <% ((@str - 1) * 10).upto(n - 1) do |i| %>
      <% a = @answer[-n+i - (@str - 1) * 10] %>
      <% if current_user && a.user_id == current_user.id%>
        <tr>
          <td><%= (a[:created_at] + 60*60*3).to_s[11..18] %></td>
          <td><%= a[:text] %></td>
          <td><%= current_user.login %></td>
        </tr>
      <% end %>
      <% if (not current_user) or a.user_id != current_user.id%>
        <tr>
          <td><%= User.find_by_id(a[:user_id]).login %></td>
          <td><%= a[:text] %></td>
          <td><%= a[:created_at].to_s[11..18] %></td>
        </tr>
      <% end %>
    <% end %>
  <%end %>
  <% if @answer.length == 0 %>
    <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
    <p> <%= t(:'Nothing here') %></p>
    </div>
    <div class="col-4"></div>
  </div>
  <%end %>
  </tbody>
</table>
<div class="row">
  <div class="col-2">
    <% if str > 1 %>
      <%= form_tag("/forums/" + @forum.id.to_s, :method => "get") do %>
        <%= hidden_field_tag(:str, str - 1) %>
        <%= submit_tag(str - 1, class: "btn btn-sm btn-outline-dark") %>
      <%end %>
    <% end %>
  </div>
  <div class="col-8">
    <% if current_user %>
      <%= form_tag("/forums/" + @forum.id.to_s, :method => "get") do %>
        <div class="row">
          <div class="col-8">
            <%= text_field_tag(:mes, "", class: "form-control form-control-sm") %>
          </div>
          <div class="col-2">
            <%= submit_tag("Отправить", class: "btn btn-sm btn-outline-dark") %>
          </div>
        </div>
      <%end %>
    <% end %>
    <% unless current_user%>
      <p class="align-content-center"><%= t(:'Login to send a message') %></p>
    <%end %>
  </div>
  <div class="col-2">
    <% if (@str) * 10 <= @answer.length %>
      <%= form_tag("/forums/" + @forum.id.to_s, :method => "get") do %>
        <%= hidden_field_tag(:str, str + 1) %>
        <%= submit_tag(@str + 1, class: "btn btn-sm btn-outline-dark") %>
      <%end %>
    <% end %>
  </div>
</div>


app/views/lang/change.html.erb
<h1>Lang#change</h1>
<p>Find me in app/views/lang/change.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HT2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar" style="background-color: black">
      <a class="navbar-brand text-white" href="/"><%= t(:'Home') %></a>
      <%= form_tag("/lang/change", :method => "get") do %>
        <%= hidden_field_tag(:l, :ru) %>
        <%= submit_tag('RU', class: "btn btn-sm btn-light") %>
      <%end %>
      <%= form_tag("/lang/change", :method => "get") do %>
        <%= hidden_field_tag(:l, :en) %>
        <%= submit_tag('ENG', class: "btn btn-sm btn-light") %>
      <%end %>
      <% if current_user %>
        <div>
          <a class="text-white"> <%= label_tag(current_user.login) %> </a>
          <a class="btn btn-sm btn-light" href= <%="/users/" + current_user.id.to_s + '/edit'%>><%= t(:'Edit') %></a>
          <a class="btn btn-sm btn-light" href="/sess/out"><%= t(:'Logout') %></a>
        </div>
      <% end %>
      <% unless current_user %>
        <a class="btn btn-sm btn-light" href="/sess/login"><%= t(:'Login') %></a>
      <% end %>
    </nav>
  </header>
  <main class="container" role="main" style="margin-top: 2em">
    <div>
      <div class="row">
        <div class="col-2 bd-sidebar" style="">
          <table class="table table-borderless">
            <thead><tr><th><%= t(:'Forums list') %></th></tr></thead>
            <tbody>
              <% Forum.find_by_sql("select * from forums").each do |a| %>
                <tr><td><%= link_to a[:name], forum_path(a[:id]) %></td></tr>
              <% end %>
            </tbody>
          </table>
          <% if current_user %>
            <a class="btn btn-sm btn-outline-dark" href="/forums/new"><%= t(:'Create forum') %></a>
          <% end %>
        </div>
        <div class="col-8">
          <%= yield %>
        </div>
        <div class="col-2">
          Здесь могла быть <br/> ваша реклама <br/> +79637210282
        </div>
      </div>
    </div>
  </main>
  </body>
</html>

app/views/main/main.html.erb
<h1> <%= t(:'Intro') %></h1>
<%= form_tag("/main/view.json", :method => "get", remote: true, id: 'main_form') do %>
  <%= label_tag(t(:'Our statistics ->')) %>
  <%= submit_tag(t(:'Find out!'), class: "btn btn-outline-dark btn-sm") %>
  <table id="result" class="table table-borderless table-striped" >

  </table>
<% end %>

app/views/sess/login.html.erb
<div class="row">
  <div class="col-4"></div>
<div class="col-4">
<%= form_tag("/sess/middle", :method => "get") do %>
    <%= label_tag("Логин:") %>
    <%= text_field_tag(:login, '', class: "form-control form-control-sm") %>
    <%= label_tag("Пароль:") %>
    <%= password_field_tag(:password, '', class: "form-control form-control-sm") %>
    <p></p>
    <%= submit_tag("Войти", class: "btn btn-sm btn-primary btn-block btn-light") %>
  <% end %>
  <p></p>
  <%= form_tag("/users/new", :method => "get") do %>
    <%= submit_tag("Зарегистрироваться", class: "btn btn-sm btn-primary btn-block btn-light") %>
  <% end %>
</div>
<div class="col-4"></div>
</div>

app/views/sess/logout.html.erb
<h1>Sess#logout</h1>
<p>Find me in app/views/sess/logout.html.erb</p>

app/views/sess/middle.html.erb
<p>Неверный логин или пароль</p>
<a class="btn btn-sm btn-outline-secondary bg-white" href="/sess/login">Войти</a>

app/views/sess/out.html.erb
<h1>Sess#out</h1>
<p>Find me in app/views/sess/out.html.erb</p>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
<%= form_with(model: user, local: true) do |form| %>
  <% if @problem %>
    <div id="error_explanation">
      <p> Нельзя создать пользователя</p>
    </div>
  <% else %>
    <% if user.errors.any? %>
     <div id="error_explanation">
       <p> Данный логин уже занят</p>
     </div>
    <%end %>
  <%end %>

  <div class="field">
    <%= form.label t(:'Login') %>
    <%= form.text_field :login, id: :user_login, class: "form-control form-control-sm"%>
  </div>

  <div class="field">
    <%= form.label t(:'Password') %>
    <%= form.text_field :password, id: :user_password, class: "form-control form-control-sm"%>
  </div>
  <p></p>
  <div class="actions">
    <%= form.submit value: t(:'Create user'),class: "btn btn-sm btn-primary btn-block btn-light" %>
  </div>
<% end %>
  </div>
  <div class="col-4"></div>
</div>

app/views/users/edit.html.erb
<% if current_user and current_user.login == @user.login %>
  <%= render 'form', user: @user %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user and current_user.login == 'admin' %>
<table>
  <thead>
    <tr>
      <th>Логин</th>
      <th>Пароль</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% if user.login == '' %>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user and current_user.login == @user.login %>
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Логин:</strong>
      <%= @user.login %>
    </p>

    <p>
      <strong>Пароль:</strong>
      <%= @user.password %>
    </p>

    <%= link_to 'Edit', edit_user_path(@user) %>
  </div>
  <div class="col-4"></div>
</div>
<% end %>